### ISSUE TITLE
Unable to retrieve tokens.

### ISSUE THREAD

**Issue by Seraphim1050** [Vap0r1ze/discord-remote-auth#13] opened 2023-09-27 09:14 UTC
I successfully scanned the QRcode, the token didn't come.

![image](https://github.com/Vap0r1ze/discord-remote-auth/assets/121426982/27f16342-170e-4534-815d-41e41f3535d2)

**Comment by Vap0r1ze** [comment] 2023-09-27 23:53
Duplicate of #12

**Closed as completed by Vap0r1ze** 2023-09-27 23:53 UTC
